all: clean

create : 
	pdflatex "defense".tex
	pdflatex "defense".tex
	
clean: create
	rm -rf *.aux  *.nav  *.vrb  *.log *.lof *.lot  *.out *.snm *.toc *.gz *.mtc* *.maf *.fls *.tmp *.bbl *.blg  *.mtc  *.bcf *.xml *.fdb_latexmk 
